### ISSUE TITLE
campo: checkbox + texto

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QPropostas#15]
Ter uma opção onde possa aparece no formato checkbox e texto.. exemplo:

Quadro de professores do curso
( ) graduação. Quantidade: ________
( ) especialização Quantidade: ________
( ) mestrado. Quantidade: ________
( ) doutorado. Quantidade: ________
( ) pós-doutorado. Quantidade: ________

e possa customizar a palavra que repetirá em todos os campos, como no exemplo "Quantidade"

**Comment by edueo** [comment]
Implementado tipo de campo checkbox + texto que implementa a funcionalidade acima
