### ISSUE TITLE
problema em título do post

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QPropostas#2]
quando zerei todos os campos, para iniciar um novo formulário, não tem um item que eu marque para que aquele campo seja titulo e texto, sabe, do padrão de posts do WP, e acaba ficando vazio ao ser submetido uma propostas.

**Comment by edueo** [comment]
Problema corrigido. Implementei o tipo de campo wp_title e wp_content que determina qual o titulo e conteudo do post respectivamente.
