### ISSUE TITLE
upload de arquivos

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QPropostas#3]
na opção de upload de outro campo que seja de arquivo em anexo, além do que fica como imagem destacada.. por exemplo, a pessoa submeter um pdf e aparecer no frontend algo escrito PDF ou o nome do arquivo e um link para baixar o mesmo.

**Comment by edueo** [comment]
Implementado campo anexo, para upload e exibição de arquivos pdf

**Comment by Quijaua** [comment]
fiquei confuso agora, a exibição é só o link (que pode ser um texto ou imagem)? ou é uma visualização na tela do pdf? porque na real é a primeira opção e pode ser pdf ou qualquer formato... algo como lê o mime type e aparece a imagem ou só o um com o nome do arquivo e como hipertexto

**Comment by edueo** [comment]
Para anexos é permitido apenas o mime application/pdf. A abertura pra
qualquer formato pode abrir brechas para fazer o upload de um arquivo exe
por exemplo e causar danos no servidor.

Att,
Eduardo Alencar

Em 1 de abril de 2015 18:16, Quijaua notifications@github.com escreveu:

**Comment by Quijaua** [comment]
OK! bacana a solução... mas é possível adicionar outras entradas?
se quiser colocar doc, xls, por exemplo?

Em 2015-04-01 18:41, Eduardo Alencar escreveu:

> Para anexos é permitido apenas o mime application/pdf. A abertura pra
>  qualquer formato pode abrir brechas para fazer o upload de um arquivo
> exe
>  por exemplo e causar danos no servidor.
> 
>  Att,
>  Eduardo Alencar
> 
>  Em 1 de abril de 2015 18:16, Quijaua notifications@github.com
> escreveu:
> 
> > fiquei confuso agora, a exibição é só o link (que pode ser um
> > texto ou
> > imagem)? ou é uma visualização na tela do pdf? porque na real é
> > a primeira
> > opção e pode ser pdf ou qualquer formato... algo como lê o mime
> > type e
> > aparece a imagem ou só o um com o nome do arquivo e como
> > hipertexto
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/Quijaua/QPropostas/issues/3#issuecomment-88633930.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/Quijaua/QPropostas/issues/3#issuecomment-88639961

## 

RAFAEL "BANTO PALMARINO" GOMES
  e-mail: rafaelgomes@quijaua.com.br
  fone: (19) 8888-0113
  Quijaua Soluções Web em Software Livre
http://www.quijaua.com.br

**Comment by edueo** [comment]
sim, vou limitar em pdf,  xls e doc ok?

Att,
Eduardo Alencar

Em 1 de abril de 2015 18:45, Quijaua notifications@github.com escreveu:

**Comment by Quijaua** [comment]
OK!

Em 2015-04-01 18:59, Eduardo Alencar escreveu:

> sim, vou limitar em pdf, xls e doc ok?
> 
>  Att,
>  Eduardo Alencar
> 
>  Em 1 de abril de 2015 18:45, Quijaua notifications@github.com
> escreveu:
> 
> > OK! bacana a solução... mas é possível adicionar outras
> > entradas?
> > se quiser colocar doc, xls, por exemplo?
> > 
> > Em 2015-04-01 18:41, Eduardo Alencar escreveu:
> > 
> > > Para anexos é permitido apenas o mime application/pdf. A
> > > abertura pra
> > > qualquer formato pode abrir brechas para fazer o upload de um
> > > arquivo
> > > exe
> > > por exemplo e causar danos no servidor.
> > > 
> > > Att,
> > > Eduardo Alencar
> > > 
> > > Em 1 de abril de 2015 18:16, Quijaua notifications@github.com
> > > escreveu:
> > > 
> > > > fiquei confuso agora, a exibição é só o link (que pode ser
> > > > um
> > > > texto ou
> > > > imagem)? ou é uma visualização na tela do pdf? porque na
> > > > real é
> > > > a primeira
> > > > opção e pode ser pdf ou qualquer formato... algo como lê o
> > > > mime
> > > > type e
> > > > aparece a imagem ou só o um com o nome do arquivo e como
> > > > hipertexto
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/Quijaua/QPropostas/issues/3#issuecomment-88633930.
> > > 
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub [1].
> > > 
> > > *
> > > 
> > > ## Links:
> > > 
> > > [1]
> > > 
> > > https://github.com/Quijaua/QPropostas/issues/3#issuecomment-88639961
> > 
> > ## 
> > 
> > RAFAEL "BANTO PALMARINO" GOMES
> > e-mail: rafaelgomes@quijaua.com.br
> > fone: (19) 8888-0113
> > Quijaua Soluções Web em Software Livre
> > http://www.quijaua.com.br
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/Quijaua/QPropostas/issues/3#issuecomment-88641263.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/Quijaua/QPropostas/issues/3#issuecomment-88645275

## 

RAFAEL "BANTO PALMARINO" GOMES
  e-mail: rafaelgomes@quijaua.com.br
  fone: (19) 8888-0113
  Quijaua Soluções Web em Software Livre
http://www.quijaua.com.br

**Comment by edueo** [comment]
Implementado

**Comment by Quijaua** [comment]
está gerando conflito entre as duas opções de upload, em imagem destacada não está aceitando no formato jpg, por exemplo.

**Comment by Quijaua** [comment]
após submeter a proposta com anexo em formato errado, aparece a mensagem "The file type that you've uploaded is not a PDF.", mas mesmo assim a proposta é inserida. Nesse caso você acha que é melhor bloquear a submissão com dado errado?

**Comment by edueo** [comment]
Corrigido conflito, acho melhor não bloquear a submissão caso o arquivo esteja fora do formartos(pdf,doc,xls).

**Comment by Quijaua** [comment]
fiz o teste e não deu certo a implementação, é enviado os dados em texto, mas o anexo e a imagem destacada não são transferidos nem aparece em banco... antes aparece o url do anexo

**Comment by edueo** [comment]
Corrigido!
