### ISSUE TITLE
Exportar em CSV

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QPropostas#5]
e por fim, aparecer um campo de exportar para csv eque todos os campos, incluindo a categoria e do arquivo em anexo aparecer o URL

**Comment by edueo** [comment]
@Quijaua Esse exportação seria geral na listagem das proposta ou especifica para uma proposta?

**Comment by Quijaua** [comment]
Exportar todos os campos de todas as propostas

**Comment by edueo** [comment]
Ok, irei implementar, acredito que esse item vou conseguir finalizar
somente amanha cedo, ok?

Att,
Eduardo Alencar

2015-04-01 18:13 GMT-03:00 Quijaua notifications@github.com:

**Comment by Quijaua** [comment]
Ok! Vou homologar as demais funções

Att.,
Rafael Gomes

Em 2015-04-01 18:42, Eduardo Alencar escreveu:

> Ok, irei implementar, acredito que esse item vou conseguir finalizar
>  somente amanha cedo, ok?
> 
>  Att,
>  Eduardo Alencar
> 
>  2015-04-01 18:13 GMT-03:00 Quijaua notifications@github.com:
> 
> > Exportar todos os campos de todas as propostas
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/Quijaua/QPropostas/issues/5#issuecomment-88633462.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/Quijaua/QPropostas/issues/5#issuecomment-88640098

## 

RAFAEL "BANTO PALMARINO" GOMES
  e-mail: rafaelgomes@quijaua.com.br
  fone: (19) 8888-0113
  Quijaua Soluções Web em Software Livre
http://www.quijaua.com.br

**Comment by edueo** [comment]
Funcionalidade implementada, basta entrar na listagem de propostas, selecionar quais deseja exportar, selecionar Exportar no combo e clicar em aplicar. Conforme figura em anexo
![Uploading export_csv.png . . .]()

**Comment by Quijaua** [comment]
ok! no caso de ter muitas propostas e habilitar a paginação no painel, ao clicar em selecionar todas serão somente da primeira página ou virão todas?

**Comment by Quijaua** [comment]
não exportou a categoria associada

**Comment by edueo** [comment]
No caso de muitas propostas serão selecionadas apenas a da página atual.

Sobre a exportação da categoria, irei corrigir.

**Comment by edueo** [comment]
Categoria associada na exportação.

**Comment by Quijaua** [comment]
quando crio um campo com select essa informação não está mais vindo no CSV

**Comment by Quijaua** [comment]
não está exportando os dados do campo "checkbox + texto"
