### ISSUE TITLE
problema ao remover campo de categoria

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QPropostas#7]
o recurso de categoria sempre aparecer e precisei comentar diretamente no código para desaparecer, isso no caso de formulário que não use categoria

**Comment by edueo** [comment]
Para formulários que não use categoria inserir o shortcode da seguinte forma:

```
[inscreva-se use_category=false]
```

**Comment by Quijaua** [comment]
testei esse recurso, mas não funcionou. não lista as categorias criadas, mas mostra o texto "Categorias de apresentacÃµes artÃ­sticas:"

**Comment by edueo** [comment]
Corrigido!
