### ISSUE TITLE
campo outros em checkbox

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QPropostas#9]
Quando um campo for checkbox ter a opção de inserir outra opção na prevista, por exemplo: que cor você gosta? ( ) amarelo ( ) verde ( )vermelho ( ) Outros _______ e após outros é possível escrever preto, por exemplo. E o texto "Outros" possa ser customizável (se alterado para Especifique, por exemplo, em outras situações).

**Comment by edueo** [comment]
Basta especificar o texto complementar na inclusão do campo que o comportamento acima será reproduzido

**Comment by Quijaua** [comment]
o campo não previsto deve aparecer logo após o texto o outro, e está aparecendo abaixo e repetido.

**Comment by edueo** [comment]
Rafael nos valores vc não precisa especificar outros. Isso vc deve colocar no campo Texto para outras opções. De qualquer forma corrigi a forma como o html do campo é renderizado
